version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:786123b72b8a1703cbab85ffca624d3f8caba2f379fe8410137dbf3630899b49

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
