version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:69a9f486aab9a7d81df4ae66b6640e925cf57474380a504b26cb4a7c18a9be8d

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
