version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:5986f812d4b2499e8fefce5423fe00b1766ed49f0246d456ba7d558d8be0be2d

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
