version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:bdbd538d2c5495e0a0c98385243fbd19f170ff42392456c3dcd9c984e12a0f2d

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
