version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:04b212ad5c613ae096cff10d2960f6fc0029a11270e32666a3b77df0e27ed79d

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
