version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8@sha256:1243397aba81f50e331dfe9bed2af23364d292a289934eaafc773a3a2c4e5ca7

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
